import { LocalizedString } from './types';

type TranslationKeys = {
    [key: string]: LocalizedString;
};

export const translations: TranslationKeys = {
    // Bottom Nav
    navServices: { ru: 'Услуги', en: 'Services', sr: 'Услуге' },
    navBookings: { ru: 'Мои записи', en: 'My Bookings', sr: 'Моје резервације' },
    navNews: { ru: 'Новости', en: 'News', sr: 'Вести' },
    navSpecialists: { ru: 'Специалисты', en: 'Specialists', sr: 'Специјалисти' },
    navProfile: { ru: 'Профиль', en: 'Profile', sr: 'Профил' },
    // Services Screen
    servicesTitle: { ru: 'Наши услуги', en: 'Our Services', sr: 'Наше услуге' },
    bookButton: { ru: 'Записаться', en: 'Book', sr: 'Резервиши' },
    priceFrom: { ru: 'от {{price}} RSD', en: 'from {{price}} RSD', sr: 'од {{price}} РСД' },
    durationMinutes: { ru: '{{duration}} мин', en: '{{duration}} min', sr: '{{duration}} мин' },
    // Service Detail Screen
    serviceDetailTitle: { ru: 'Об услуге', en: 'Service Details', sr: 'Детаљи услуге' },
    specialistsForService: { ru: 'Специалисты, выполняющие эту услугу:', en: 'Specialists who perform this service:', sr: 'Специјалисти који врше ову услугу:' },
    bookNow: { ru: 'Записаться сейчас', en: 'Book Now', sr: 'Резервиши сада' },
    // Specialists Screen
    specialistsTitle: { ru: 'Наши специалисты', en: 'Our Specialists', sr: 'Наши специјалисти' },
    // Booking Flow
    bookingTitle: { ru: 'Запись на услугу', en: 'Book a Service', sr: 'Резервација услуге' },
    chooseSpecialist: { ru: 'Выберите специалиста', en: 'Choose a Specialist', sr: 'Изаберите специјалисту' },
    anySpecialist: { ru: 'Любой специалист', en: 'Any Specialist', sr: 'Било који специјалиста' },
    chooseDateTime: { ru: 'Выберите дату и время', en: 'Choose Date and Time', sr: 'Изаберите датум и време' },
    confirmBooking: { ru: 'Подтвердить запись', en: 'Confirm Booking', sr: 'Потврди резервацију' },
    bookingConfirmed: { ru: 'Запись подтверждена!', en: 'Booking Confirmed!', sr: 'Резервација је потврђена!' },
    backButton: { ru: 'Назад', en: 'Back', sr: 'Назад' },
    noAvailableSlots: { ru: 'Нет доступных слотов', en: 'No available slots', sr: 'Нема доступних термина' },
    timeOfDay: { ru: 'Время суток', en: 'Time of Day', sr: 'Доба дана' },
    anyTime: { ru: 'Любое', en: 'Any', sr: 'Било које' },
    morning: { ru: 'Утро', en: 'Morning', sr: 'Јутро' },
    afternoon: { ru: 'День', en: 'Afternoon', sr: 'Поподне' },
    evening: { ru: 'Вечер', en: 'Evening', sr: 'Вече' },
    bookingDurationInfo: { ru: 'Длительность: {{duration}} мин (+10 мин перерыв)', en: 'Duration: {{duration}} min (+10 min break)', sr: 'Трајање: {{duration}} мин (+10 мин паузе)' },
    // My Bookings
    myBookingsTitle: { ru: 'Мои записи', en: 'My Bookings', sr: 'Моје резервације' },
    upcoming: { ru: 'Предстоящие', en: 'Upcoming', sr: 'Предстојеће' },
    past: { ru: 'Прошедшие', en: 'Past', sr: 'Прошле' },
    cancelBooking: { ru: 'Отменить запись', en: 'Cancel Booking', sr: 'Откажи резервацију' },
    cancellationPolicy: { ru: 'Отмена возможна не позднее, чем за 24 часа.', en: 'Cancellation is possible no later than 24 hours in advance.', sr: 'Отказивање је могуће најкасније 24 сата унапред.' },
    leaveReview: { ru: 'Оставить отзыв', en: 'Leave a Review', sr: 'Оставите рецензију' },
    // News
    newsTitle: { ru: 'Новости и акции', en: 'News & Promotions', sr: 'Вести и промоције' },
    promotion: { ru: 'Акция', en: 'Promotion', sr: 'Промоција' },
    // Profile
    profileTitle: { ru: 'Личный кабинет', en: 'Personal Cabinet', sr: 'Лични кабинет' },
    yourName: { ru: 'Ваше имя', en: 'Your Name', sr: 'Ваше име' },
    phone: { ru: 'Телефон', en: 'Phone', sr: 'Телефон' },
    saveChanges: { ru: 'Сохранить изменения', en: 'Save Changes', sr: 'Сачувај промене' },
    adminPanel: { ru: 'Админ-панель', en: 'Admin Panel', sr: 'Админ панел' },
    enterKeyword: { ru: 'Введите ключевое слово', en: 'Enter keyword', sr: 'Унесите кључну реч' },
    login: { ru: 'Войти', en: 'Login', sr: 'Пријава' },
    adminPassword: { ru: 'Пароль администратора', en: 'Admin Password', sr: 'Администраторска лозинка' },
    // Admin Dashboard
    dashboardTitle: { ru: 'Панель управления', en: 'Dashboard', sr: 'Контролна табла' },
    totalServices: { ru: 'Всего услуг', en: 'Total Services', sr: 'Укупно услуга' },
    totalSpecialists: { ru: 'Всего специалистов', en: 'Total Specialists', sr: 'Укупно специјалиста' },
    upcomingBookings: { ru: 'Предстоящие записи', en: 'Upcoming Bookings', sr: 'Предстојеће резервације' },
    totalPublications: { ru: 'Всего публикаций', en: 'Total Publications', sr: 'Укупно објава' },
     // Admin Panel - Schedule
    scheduleManagementTitle: { ru: 'Управление расписанием', en: 'Schedule Management', sr: 'Управљање распоредом' },
    pendingRequests: { ru: 'Ожидающие запросы', en: 'Pending Requests', sr: 'Захтеви на чекању' },
    approve: { ru: 'Одобрить', en: 'Approve', sr: 'Одобри' },
    reject: { ru: 'Отклонить', en: 'Reject', sr: 'Одбиј' },
    noPendingRequests: { ru: 'Нет ожидающих запросов.', en: 'No pending requests.', sr: 'Нема захтева на чекању.' },
    selectSpecialist: { ru: 'Выберите специалиста', en: 'Select a Specialist', sr: 'Изаберите специјалисту' },
    editSchedule: { ru: 'Редактировать расписание', en: 'Edit Schedule', sr: 'Уреди распоред' },
    mySchedule: { ru: 'Мое расписание', en: 'My Schedule', sr: 'Мој распоред' },
    requestChange: { ru: 'Запросить изменение', en: 'Request a Change', sr: 'Затражите измену' },
    newWorkHours: { ru: 'Новые рабочие часы', en: 'New Work Hours', sr: 'Ново радно време' },
    newWorkHoursHelp: { ru: 'Введите время через запятую. Оставьте пустым для выходного.', en: 'Enter times separated by comma. Leave blank for a day off.', sr: 'Унесите времена одвојена зарезом. Оставите празно за слободан дан.' },
    reasonForChange: { ru: 'Причина изменения', en: 'Reason for change', sr: 'Разлог за измену' },
    submitRequest: { ru: 'Отправить запрос', en: 'Submit Request', sr: 'Пошаљи захтев' },
    myRequests: { ru: 'Мои запросы', en: 'My Requests', sr: 'Моји захтеви' },
    clearDay: { ru: 'Очистить день', en: 'Clear Day', sr: 'Очисти дан' },
    dayOff: { ru: 'Выходной', en: 'Day Off', sr: 'Слободан дан' },
    // Admin Panel - Publications
    publicationManagementTitle: { ru: 'Управление публикациями', en: 'Publication Management', sr: 'Управљање објавама' },
    addPublication: { ru: 'Добавить публикацию', en: 'Add Publication', sr: 'Додај објаву' },
    editPublication: { ru: 'Редактировать публикацию', en: 'Edit Publication', sr: 'Уреди објаву' },
    publicationType: { ru: 'Тип публикации', en: 'Publication Type', sr: 'Тип објаве' },
    news: { ru: 'Новость', en: 'News', sr: 'Вест' },
    promo: { ru: 'Акция', en: 'Promotion', sr: 'Промоција' },
    title: { ru: 'Заголовок', en: 'Title', sr: 'Наслов' },
    text: { ru: 'Текст', en: 'Text', sr: 'Текст' },
    imageURL: { ru: 'URL изображения', en: 'Image URL', sr: 'УРЛ слике' },
    publishDate: { ru: 'Дата публикации', en: 'Publish Date', sr: 'Датум објаве' },
    promoPeriod: { ru: 'Период акции', en: 'Promotion Period', sr: 'Период промоције' },
    promoStart: { ru: 'Начало', en: 'Start', sr: 'Почетак' },
    promoEnd: { ru: 'Конец', en: 'End', sr: 'Крај' },
    // Admin Panel - Statistics
    statisticsTitle: { ru: 'Статистика', en: 'Statistics', sr: 'Статистика' },
    startDate: { ru: 'Дата начала', en: 'Start Date', sr: 'Датум почетка' },
    endDate: { ru: 'Дата окончания', en: 'End Date', sr: 'Датум завршетка' },
    filterBy: { ru: 'Фильтровать по', en: 'Filter By', sr: 'Филтрирај по' },
    specialist: { ru: 'Специалисту', en: 'Specialist', sr: 'Специјалиста' },
    service: { ru: 'Услуге', en: 'Service', sr: 'Услуга' },
    selectOption: { ru: 'Выберите опцию', en: 'Select an option', sr: 'Изаберите опцију' },
    generateReport: { ru: 'Сформировать отчет', en: 'Generate Report', sr: 'Генериши извештај' },
    reportResults: { ru: 'Результаты отчета', en: 'Report Results', sr: 'Резултати извештаја' },
    totalBookingsReport: { ru: 'Всего записей', en: 'Total Bookings', sr: 'Укупно резервација' },
    totalRevenueReport: { ru: 'Общий доход', en: 'Total Revenue', sr: 'Укупан приход' },
    detailedListOfBookings: { ru: 'Детальный список записей', en: 'Detailed List of Bookings', sr: 'Детаљан списак резервација' },
    date: { ru: 'Дата', en: 'Date', sr: 'Датум' },
    noBookingsFound: { ru: 'Записи не найдены.', en: 'No bookings found.', sr: 'Нема пронађених резервација.' },
     // Admin Panel - Reviews
    reviewManagementTitle: { ru: 'Управление отзывами', en: 'Review Management', sr: 'Управљање рецензијама' },
    pendingReviews: { ru: 'Ожидающие отзывы', en: 'Pending Reviews', sr: 'Рецензије на чекању' },
    approvedReviews: { ru: 'Одобренные отзывы', en: 'Approved Reviews', sr: 'Одобрене рецензије' },
    noPendingReviews: { ru: 'Нет отзывов для модерации.', en: 'No reviews to moderate.', sr: 'Нема рецензија за модерирање.' },
    noApprovedReviews: { ru: 'Нет одобренных отзывов.', en: 'No approved reviews.', sr: 'Нема одобрених рецензија.' },
    unapprove: { ru: 'Снять с публикации', en: 'Unapprove', sr: 'Повуци објаву' },
    forSpecialist: { ru: 'для', en: 'for', sr: 'за' },
};